package com.indra.finance.error;

public enum Error {
	THE_CLIENT_HAS_NOT_DUTIES, THE_DUTY_DOESNT_EXIST, THE_DUTY_IS_DISABLED, THE_CLIENT_ALREADY_EXIST,
	THE_CLIENT_DOESNT_EXIST, THE_CLIENT_IS_DISABLED, THERE_ARENT_PAYMENTS_FOR_THIS_DUTY, THE_DUTY_HAS_ALREADY_BEEN_PAID,
	THE_PAYMENT_EXCEED_THE_VALUE
}